spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/board?useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1q2w3e4r

server:
  port: 80

aes256:
  encrypt-key:
    member-login: projectminiboardmemberloginkey!@
    attach-file: projectminiboardattachfilekey!@#

file:
  save-base-dir: /Users/kchangwook/Documents/