spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/board?useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234

mybatis:
  type-aliases-package: project.mini.board
  mapper-locations: classpath:/main/java/project/mini/board/**/mapper/**.xml